FROM node:4.2.2

MAINTAINER Zane McCaig

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# expose our port
EXPOSE 3000
EXPOSE 3443

# Prepare for staging 
ENV NODE_ENV staging 
ENV ENCRYPT_PASSWORD couchesareabit2fly4me

COPY package.json /usr/src/app/
RUN npm install && npm install -g grunt-cli
COPY . /usr/src/app

# Run the application
CMD grunt coverage
